### PR TITLE
feat(update_all_gobin): add script

### LINKED ISSUE #2: add `update_all_gobin` script
as a developer, I don't want to manually `ugbt install` each time there is an update, I want to run a command that will update all of the actions in one sweep.

I am planning on submitting a PR for this. feel free to review

I also want #1 to only install stable versions

### PR DESCRIPTION
**Pull request by georgettica**
closes https://github.com/kortschak/ugbt/issues/2

### CODE REVIEW

**Review by kortschak — COMMENTED** [review]
Thanks for the contribution, but I don't want to add scripts to this. Can I suggest that you keep this as a wrapper for your own use.

**Comment by georgettica** [comment]
I'll do that, but maybe I'll try and convert it to golang and incorporate?

**Comment by kortschak** [comment]
I'm not sure. I'll have a think. The whole approach here is quite inefficient from a network usage perspective. This could potentially be made more efficient with the use of some heuristics about the relationship between time and version, so I'd like to look into that before it starts being used as a global updater.

**Comment by kortschak** [comment]
I'll close this, but leave the issue open.

**Pull request closed without merging**
